---
##############################################################################
# Ansible metadata for `capykit.image` role
##############################################################################

allow_duplicates: no

dependencies: []
# - role: role_name
