---
##############################################################################
# Main tasks for `capykit.image` role
##############################################################################

- set_fact:
    capykit_path: >-
      {{ role_path | path_resolve( '..', '..', '..' ) }}


- name: >-
    Ensure `capykit` image is present
    (based off `{{ capykit_image_from.string }}`)
  capykit._image:
    
    path: >-
      {{ capykit_path }}
      
    from_image: >-
      {{ capykit_image_from }}
      
    fact_name: >-
      {{ capykit_image_fact_name }}
  
  register: capykit_image_args
